
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Sep 15 22:00:41 CEST 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 45;
  public static final int DIVEQ = 43;
  public static final int DVOTACKA = 48;
  public static final int CHAR = 51;
  public static final int CONST = 22;
  public static final int MODEQ = 44;
  public static final int LMEDBRACE = 13;
  public static final int LOWER = 18;
  public static final int LOWEQ = 37;
  public static final int LPAREN = 7;
  public static final int GREATER = 17;
  public static final int SEMI = 6;
  public static final int CONTINUE = 28;
  public static final int GREATEQ = 36;
  public static final int MULI = 31;
  public static final int FOR = 26;
  public static final int MINUS = 30;
  public static final int STATIC = 29;
  public static final int RPAREN = 8;
  public static final int AND = 38;
  public static final int OR = 39;
  public static final int BOOL = 52;
  public static final int COMMA = 9;
  public static final int CLASS = 20;
  public static final int PLUSEQ = 40;
  public static final int MINUSEQ = 41;
  public static final int PLUS = 12;
  public static final int IF = 23;
  public static final int DOT = 15;
  public static final int TARABA = 49;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 46;
  public static final int MODI = 33;
  public static final int RETURN = 11;
  public static final int EQUAL = 16;
  public static final int NEW = 24;
  public static final int error = 1;
  public static final int EQEQ = 34;
  public static final int NUMBER = 50;
  public static final int IDENT = 53;
  public static final int BREAK = 19;
  public static final int VOID = 3;
  public static final int DIVI = 32;
  public static final int MULEQ = 42;
  public static final int RMEDBRACE = 14;
  public static final int LBRACE = 4;
  public static final int ELSE = 21;
  public static final int READ = 25;
  public static final int RBRACE = 5;
  public static final int EXTENDS = 27;
  public static final int PROG = 2;
  public static final int DOLAR = 47;
  public static final int PRINT = 10;
  public static final int NOTEQ = 35;
}

